
####
# Enable rails rules
####
Rails:
  Enabled: true

####
# Global rules
####
AllCops:
  Exclude:
    - '.chefrepo/**/*'
    - '.vagrant/**/*'
    - '.git/**/*'
    - 'node_modules/**/*'
    - 'tungsten/**/*'
    - 'tungsten-support/**/*'
    - 'vendor/**/*'
    - Vagrantfile
    - Guardfile

  # Enable new rules only if validated by Captive (or Airbnb via inherited_from)
  DisabledByDefault: true


####
# Include every files
####
inherit_from:
  - './rubocop-default.yml'
  - './rubocop-bundler.yml'
  - './rubocop-gemspec.yml'
  - './rubocop-layout.yml'
  - './rubocop-lint.yml'
  - './rubocop-metrics.yml'
  - './rubocop-naming.yml'
  - './rubocop-performance.yml'
  - './rubocop-rails.yml'
  - './rubocop-rspec.yml'
  - './rubocop-security.yml'
  - './rubocop-style.yml'
