inherit_from:
  # @see https://github.com/airbnb/ruby/blob/main/rubocop-airbnb/config/rubocop-style.yml
  - ./__private__/rubocop-style.yml

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
