require:
  - rubocop-magic_numbers

MagicNumbers/NoArgument:
  Enabled: true
  PermittedValues:
    - 0
    - -1
    - 1
  Exclude:
    - '**/spec/**/*.rb'
    - '**/test/**/*.rb'
    - '**/*_spec.rb'
    - '**/*_test.rb'
    - db/migrate/*.rb
    - config/**/*
    - '**/config/**/*'

# Cette règle empeche de pouvoir faire des variables d'instances qui servent de compteur
MagicNumbers/NoAssignment:
  Enabled: false
  Exclude:
    - spec/**/*_spec.rb
    - test/**/*_test.rb

MagicNumbers/NoDefault:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb
    - test/**/*_test.rb

MagicNumbers/NoReturn:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb
    - test/**/*_test.rb
