inherit_from:
  # @see https://github.com/airbnb/ruby/blob/main/rubocop-airbnb/config/rubocop-layout.yml
  - ./__private__/rubocop-layout.yml

Layout/DotPosition:
  EnforcedStyle: leading

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Layout/ArgumentAlignment:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineMethodParameterLineBreaks:
  Enabled: true

Layout/LineLength:
  # Disable LineLength on comments
  AllowedPatterns: ['^(\s*#)']
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
    - '**/*_spec.rb'
    - '**/*_test.rb'
