inherit_from:
  # @see https://github.com/airbnb/ruby/blob/main/rubocop-airbnb/config/rubocop-rspec.yml
  - ./__private__/rubocop-rspec.yml

RSpec/Focus:
  Enabled: true

# exclue certains fichiers pour simplifier l'utilisation de rswag
RSpec/ScatteredSetup:
  Exclude:
    - 'spec/requests/**/*'

RSpec/RepeatedExample:
  Exclude:
    - 'spec/requests/**/*'

RSpec/ContextWording:
  Enabled: true
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - quand
    - avec
    - sans
    - si
    - sauf si
    - pour
