inherit_from:
  # @see https://github.com/airbnb/ruby/blob/main/rubocop-airbnb/config/rubocop-rails.yml
  - ./__private__/rubocop-rails.yml

Rails/ActionControllerFlashBeforeRender:
  Enabled: true

Rails/ActionControllerTestCase:
  Enabled: false

Rails/ActionOrder:
  Enabled: true
