inherit_from:
  # @see https://github.com/airbnb/ruby/blob/main/rubocop-airbnb/config/rubocop-rspec.yml
  - ./__private__/rubocop-rspec.yml

RSpec/Focus:
  Enabled: true

# exclue certains fichiers pour simplifier l'utilisation de rswag
RSpec/ScatteredSetup:
  Exclude:
    - 'spec/requests/**/*'

RSpec/RepeatedExample:
  Exclude:
    - 'spec/requests/**/*'
