require:
  - ../lib/rubocop/cop/captive/active_admin/active_admin_addons_presence.rb
  - ../lib/rubocop/cop/captive/translation/devise_i18n_presence.rb
  - ../lib/rubocop/cop/captive/translation/rails_i18n_presence.rb
  - ../lib/rubocop/cop/captive/translation/kaminari_i18n_presence.rb
  - ../lib/rubocop/cop/captive/rspec/specify_before_parameter.rb
  - ../lib/rubocop/cop/captive/string_where_in_scope.rb
  - ../lib/rubocop/cop/captive/no_app_env.rb

# ActiveAdmin
Captive/ActiveAdmin/ActiveAdminAddonsPresence:
  Description: 'The gem `activeadmin_addons` should be added to the Gemfile if `activeadmin` is present in Gemfile'
  Include:
    - 'Gemfile'

# Translation
Captive/Translation/DeviseI18nPresence:
  Description: 'The gem `devise-i18n` should be added to the Gemfile if `devise` is present in Gemfile'
  Include:
    - 'Gemfile'

Captive/Translation/RailsI18nPresence:
  Description: 'The gem `rails-i18n` should be added to the Gemfile if `rails` is present in Gemfile'
  Include:
    - 'Gemfile'

Captive/Translation/KaminariI18nPresence:
  Description: 'The gem `kaminari-i18n` should be added to the Gemfile if `kaminari` is present in Gemfile'
  Include:
    - 'Gemfile'

# RSpec
Captive/RSpec/SpecifyBeforeParameter:
  Description: 'Specify the parameter in `before` blocks. Example : before(:each) or before(:all)'
  Include:
    - 'spec/**/*'

# other
Captive/StringWhereInScope:
  Description: 'The `where` method should be used in a scope in a model.'
  Exclude:
    - 'app/models/**/*'

Captive/NoAppEnv:
  Description: "Do not use `APP_ENV` environment variable as it conflicts with standard Rails/Rack environment variable `RAILS_ENV`."
