# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  merge_group: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

# defaults:
#   run:
#     working-directory: rubocop-airbnb

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: # use bundler 2.3 for ruby versions < 2.6 (https://bundler.io/compatibility.html)
        - ruby-version: 2.7
          bundler-version: latest
        - ruby-version: 3.0
          bundler-version: latest
        - ruby-version: 3.1
          bundler-version: latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@5311f05890856149502132d25c4a24985a00d426 # v1.153.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: ${{ matrix.bundler-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      #   working-directory: rubocop-airbnb
    # - name: Run rspec
    #   run: bundle exec rspec
    - name: Run rubocop
      run: |
        bundle exec rubocop -V
        bundle exec rubocop --config .rubocop.yml --fail-fast -d
